Repository ChimeraPy/Engine, pull requests merged in 2023-02, with the labels that each got.

#80 Configure `readthedocs` build for documentation. Closes #79
  .github/workflows/doc.yml
  .readthedocs.yml
Labels: documentation

#82 Extract hard-coded variables, improves error handling, and shifts Manager->Worker comms to use HTTP. Closes #70 #73
  .github/workflows/test.yml
  MANIFEST.in
  chimerapy/__init__.py
  chimerapy/__version__.py
  chimerapy/_logger.py
  chimerapy/chimerapyrc.yaml
  chimerapy/config.py
  chimerapy/logreceiver.py
  chimerapy/manager.py
  chimerapy/networking/client.py
  chimerapy/networking/enums.py
  chimerapy/networking/publisher.py
  chimerapy/networking/server.py
  chimerapy/node.py
  chimerapy/utils.py
  chimerapy/worker.py
  examples/remote_camera.py
  examples/remote_screen_and_web.py
  pyproject.toml
  test/conftest.py
  test/networking/test_client_server.py
  test/networking/test_code_delivery.py
  test/networking/test_connectivity.py
  test/networking/test_p2p_networking.py
  test/networking/test_subscriber_publisher.py
  test/streams/test_direct_av.py
  test/streams/test_transfer.py
  test/test_error_handling.py
  test/test_node_interactions.py
  test/test_use_cases.py
  test/test_worker_node_interactions.py
Labels: enhancement

#95 91 UUID
  chimerapy/chimerapyrc.yaml
  chimerapy/entry/worker.py
  chimerapy/graph.py
  chimerapy/manager.py
  chimerapy/networking/client.py
  chimerapy/networking/server.py
  chimerapy/node.py
  chimerapy/worker.py
  test/conftest.py
  test/mock/dockered_worker.py
  test/networking/test_client_server.py
  test/networking/test_code_delivery.py
  test/networking/test_connectivity.py
  test/networking/test_p2p_networking.py
  test/streams/test_transfer.py
  test/test_entrypoint.py
  test/test_error_handling.py
  test/test_node_interactions.py
  test/test_pipeline.py
  test/test_threaded_async.py
  test/test_use_cases.py
  test/test_worker_node_interactions.py
Labels: enhancement

#112 Convert WS Comms from Pickled Python Objects to JSON Format. Closes #105
  chimerapy/manager.py
  chimerapy/networking/client.py
  chimerapy/networking/data_chunk.py
  chimerapy/networking/enums.py
  chimerapy/networking/server.py
  chimerapy/node.py
  chimerapy/utils.py
  chimerapy/worker.py
  test/networking/test_client_server.py
  test/test_data_chunk.py
  test/test_entrypoint.py
Labels: enhancement

#114 ``get_ip_address`` bug when not connected to network. Closes #110
  chimerapy/utils.py
Labels: bug

#119 Update examples to use ID-based systems. Closes #118
  examples/remote_camera.py
  examples/remote_screen_and_web.py
  examples/remote_simple.py
  pyproject.toml
Labels: bug

#115 Refactor API handlers from ``Manager`` to separate module. Closes #109
  chimerapy/api.py
  chimerapy/manager.py
  chimerapy/networking/server.py
Labels: maintainence

#116 ``Node`` updates transferred to ``Manager`` and relay to the front-end. Closes #92
  chimerapy/api.py
  chimerapy/manager.py
  chimerapy/networking/enums.py
  chimerapy/networking/server.py
  test/front_end_integration/test_ws.py
Labels: enhancement
